### PR TITLE
Update build

### PR DESCRIPTION
**Pull request by SuperQ**
* Bump all vendoring to latest.
* Update to Go 1.15.
* Remove inline vendor dir.
* Update minimum Go version to 1.13.
* Add `update-go-deps` Makefile helper.
* Drop Travis support.

Signed-off-by: Ben Kochie <superq@gmail.com>

### CODE REVIEW

**Comment by SuperQ** [comment]
It looks like PR builds aren't enabled here.

**Comment by ncabatoff** [comment]
> It looks like PR builds aren't enabled here.

Whoops, that was unintentional.  I've toggled the setting in circleci.

**Comment by ncabatoff** [comment]
This looks good, though it needs the same s/prometheus/promhttp/ for Handler that you did on fakescraper.  Can you remove the .travis.yml while you're at it please?  I don't use Travis anymore.

Thanks for doing this!  I'll make a new release once this is merged.

**Comment by SuperQ** [comment]
Ahh, yes, I had the promhttp thing pending in my branch.

**Comment by SuperQ** [comment]
Ok, pushed promhttp fix and dropped Travis.

**Comment by ncabatoff** [comment]
Not sure why we're not seeing builds in CircleCI for your branch, but maybe the setting had to be on when the PR was opened?  Anyway, I've tested locally, and if for some reason there are problems in circleci once merged I'll fix them.

**Pull request merged**
